# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from udg.api import device_pb2 as udg_dot_api_dot_device__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in udg/api/device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Execute = channel.unary_unary(
                '/udg.DeviceGateway/Execute',
                request_serializer=udg_dot_api_dot_device__pb2.CommandRequest.SerializeToString,
                response_deserializer=udg_dot_api_dot_device__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/udg.DeviceGateway/ListDevices',
                request_serializer=udg_dot_api_dot_device__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=udg_dot_api_dot_device__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.WriteSerial = channel.unary_unary(
                '/udg.DeviceGateway/WriteSerial',
                request_serializer=udg_dot_api_dot_device__pb2.SerialWriteRequest.SerializeToString,
                response_deserializer=udg_dot_api_dot_device__pb2.SerialWriteResponse.FromString,
                _registered_method=True)
        self.ReadSerial = channel.unary_unary(
                '/udg.DeviceGateway/ReadSerial',
                request_serializer=udg_dot_api_dot_device__pb2.SerialReadRequest.SerializeToString,
                response_deserializer=udg_dot_api_dot_device__pb2.SerialReadResponse.FromString,
                _registered_method=True)
        self.SetSerialConfig = channel.unary_unary(
                '/udg.DeviceGateway/SetSerialConfig',
                request_serializer=udg_dot_api_dot_device__pb2.SerialConfigRequest.SerializeToString,
                response_deserializer=udg_dot_api_dot_device__pb2.SerialConfigResponse.FromString,
                _registered_method=True)
        self.GetSerialConfig = channel.unary_unary(
                '/udg.DeviceGateway/GetSerialConfig',
                request_serializer=udg_dot_api_dot_device__pb2.SerialConfigRequest.SerializeToString,
                response_deserializer=udg_dot_api_dot_device__pb2.SerialConfigResponse.FromString,
                _registered_method=True)
        self.ListSerialPorts = channel.unary_unary(
                '/udg.DeviceGateway/ListSerialPorts',
                request_serializer=udg_dot_api_dot_device__pb2.ListSerialPortsRequest.SerializeToString,
                response_deserializer=udg_dot_api_dot_device__pb2.ListSerialPortsResponse.FromString,
                _registered_method=True)


class DeviceGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteSerial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadSerial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSerialConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSerialConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSerialPorts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=udg_dot_api_dot_device__pb2.CommandRequest.FromString,
                    response_serializer=udg_dot_api_dot_device__pb2.CommandResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=udg_dot_api_dot_device__pb2.ListDevicesRequest.FromString,
                    response_serializer=udg_dot_api_dot_device__pb2.ListDevicesResponse.SerializeToString,
            ),
            'WriteSerial': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteSerial,
                    request_deserializer=udg_dot_api_dot_device__pb2.SerialWriteRequest.FromString,
                    response_serializer=udg_dot_api_dot_device__pb2.SerialWriteResponse.SerializeToString,
            ),
            'ReadSerial': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadSerial,
                    request_deserializer=udg_dot_api_dot_device__pb2.SerialReadRequest.FromString,
                    response_serializer=udg_dot_api_dot_device__pb2.SerialReadResponse.SerializeToString,
            ),
            'SetSerialConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSerialConfig,
                    request_deserializer=udg_dot_api_dot_device__pb2.SerialConfigRequest.FromString,
                    response_serializer=udg_dot_api_dot_device__pb2.SerialConfigResponse.SerializeToString,
            ),
            'GetSerialConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSerialConfig,
                    request_deserializer=udg_dot_api_dot_device__pb2.SerialConfigRequest.FromString,
                    response_serializer=udg_dot_api_dot_device__pb2.SerialConfigResponse.SerializeToString,
            ),
            'ListSerialPorts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSerialPorts,
                    request_deserializer=udg_dot_api_dot_device__pb2.ListSerialPortsRequest.FromString,
                    response_serializer=udg_dot_api_dot_device__pb2.ListSerialPortsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'udg.DeviceGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('udg.DeviceGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udg.DeviceGateway/Execute',
            udg_dot_api_dot_device__pb2.CommandRequest.SerializeToString,
            udg_dot_api_dot_device__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udg.DeviceGateway/ListDevices',
            udg_dot_api_dot_device__pb2.ListDevicesRequest.SerializeToString,
            udg_dot_api_dot_device__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteSerial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udg.DeviceGateway/WriteSerial',
            udg_dot_api_dot_device__pb2.SerialWriteRequest.SerializeToString,
            udg_dot_api_dot_device__pb2.SerialWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadSerial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udg.DeviceGateway/ReadSerial',
            udg_dot_api_dot_device__pb2.SerialReadRequest.SerializeToString,
            udg_dot_api_dot_device__pb2.SerialReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSerialConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udg.DeviceGateway/SetSerialConfig',
            udg_dot_api_dot_device__pb2.SerialConfigRequest.SerializeToString,
            udg_dot_api_dot_device__pb2.SerialConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSerialConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udg.DeviceGateway/GetSerialConfig',
            udg_dot_api_dot_device__pb2.SerialConfigRequest.SerializeToString,
            udg_dot_api_dot_device__pb2.SerialConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSerialPorts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/udg.DeviceGateway/ListSerialPorts',
            udg_dot_api_dot_device__pb2.ListSerialPortsRequest.SerializeToString,
            udg_dot_api_dot_device__pb2.ListSerialPortsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
