# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x12\x03udg\"\xa6\x01\n\x07\x43ommand\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\x12(\n\x06params\x18\x04 \x03(\x0b\x32\x18.udg.Command.ParamsEntry\x12\x12\n\ntimeout_ms\x18\x05 \x01(\x05\x1a-\n\x0bParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"0\n\x0e\x43ommandRequest\x12\x1e\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x0c.udg.Command\"\x9d\x01\n\rCommandResult\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0e\n\x06output\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12\x12\n\nerror_code\x18\x07 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x08 \x01(\x05\"6\n\x0f\x43ommandResponse\x12#\n\x07results\x18\x01 \x03(\x0b\x32\x12.udg.CommandResult\"@\n\x06\x44\x65vice\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\x14\n\x12ListDevicesRequest\"3\n\x13ListDevicesResponse\x12\x1c\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x0b.udg.Device2\x87\x01\n\rDeviceGateway\x12\x34\n\x07\x45xecute\x12\x13.udg.CommandRequest\x1a\x14.udg.CommandResponse\x12@\n\x0bListDevices\x12\x17.udg.ListDevicesRequest\x1a\x18.udg.ListDevicesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND_PARAMSENTRY']._loaded_options = None
  _globals['_COMMAND_PARAMSENTRY']._serialized_options = b'8\001'
  _globals['_COMMAND']._serialized_start=22
  _globals['_COMMAND']._serialized_end=188
  _globals['_COMMAND_PARAMSENTRY']._serialized_start=143
  _globals['_COMMAND_PARAMSENTRY']._serialized_end=188
  _globals['_COMMANDREQUEST']._serialized_start=190
  _globals['_COMMANDREQUEST']._serialized_end=238
  _globals['_COMMANDRESULT']._serialized_start=241
  _globals['_COMMANDRESULT']._serialized_end=398
  _globals['_COMMANDRESPONSE']._serialized_start=400
  _globals['_COMMANDRESPONSE']._serialized_end=454
  _globals['_DEVICE']._serialized_start=456
  _globals['_DEVICE']._serialized_end=520
  _globals['_LISTDEVICESREQUEST']._serialized_start=522
  _globals['_LISTDEVICESREQUEST']._serialized_end=542
  _globals['_LISTDEVICESRESPONSE']._serialized_start=544
  _globals['_LISTDEVICESRESPONSE']._serialized_end=595
  _globals['_DEVICEGATEWAY']._serialized_start=598
  _globals['_DEVICEGATEWAY']._serialized_end=733
# @@protoc_insertion_point(module_scope)
